flux-plugin: Enable/Disable force reconciliation
headlamp-k8s/plugins pull request #124
Opened 2024-12-10 09:31 UTC by ashu8912

2024-12-10 09:33 UTC, ashu8912 commented
fixes #122

2024-12-17 11:20 UTC, joaquimrocha requested changes
Besides making just one component, the commit should be prefixed with the plugin name `flux:`, not `flux-plugin:`.

2024-12-17 11:20 UTC, joaquimrocha commented on flux/src/actions/index.tsx
> +function DisableForceReconciliation(props) {
Seems like this component is the same as above, just with different logic + strings based on whether it's enable/disable. I think we should just have one single component.

2024-12-18 13:32 UTC, joaquimrocha requested changes

2024-12-18 13:32 UTC, joaquimrocha commented on flux/src/actions/index.tsx
> +  }
This will prevent the component from rendering if the force is false.

2024-12-18 13:32 UTC, joaquimrocha commented on flux/src/actions/index.tsx
> +                  `Successfully ${forceReconciliationType}d force reconciliation for ${resource.metadata.name}`,
As a general rule, never generate words for human readable messages like this. Just use `Disabled force reconciliation for ${resource.metadata.name}` and `Enabled force reconciliation for ${resource.metadata.name}`

2024-12-18 13:32 UTC, joaquimrocha commented on flux/src/actions/index.tsx
> +                enqueueSnackbar(`Failed to ${forceReconciliationType} force reconciliation for ${resource.metadata.name}`, {
Same about not generating english words from variables.

2024-12-18 13:32 UTC, joaquimrocha commented on flux/src/actions/index.tsx
> +                `Failed to ${forceReconciliationType} force reconciliation for ${resource.metadata.name} error ${error}`,
`Failed to enable force reconciliation for ${resource.metadata.name}: ${error}`
and
`Failed to disable force reconciliation for ${resource.metadata.name}: ${error}`

2024-12-18 13:32 UTC, joaquimrocha commented on flux/src/actions/index.tsx
> +        description={`Are you sure you want to ${forceReconciliationType} force reconciliation?`}
ditto

2024-12-19 13:57 UTC, merged