Add cert-manager plugin
headlamp-k8s/plugins pull request #143
Opened 2024-12-30 08:33 UTC by yolossn

2025-01-24 20:23 UTC, juv commented
This is great 👍

2025-01-29 14:35 UTC, joaquimrocha requested changes
Left a couple of small comments. The plugin should also display a special error if the cert-manager is not installed.

2025-01-29 14:35 UTC, joaquimrocha commented on cert-manager/README.md
> +- [Plugin Examples](https://github.com/headlamp-k8s/headlamp/tree/main/plugins/examples), Example plugins you can look at to see how it's done.
Let's remove this?

2025-01-29 14:35 UTC, joaquimrocha commented on cert-manager/package.json
> +  "version": "0.0.1",
I know this is the default version from headlamp-plugin but let's make it 0.1.0. I will change the default in headlamp-plugin.

2025-01-29 14:35 UTC, joaquimrocha commented on cert-manager/src/components/certificates/Detail.tsx
> +                      getter: item => item.lastTransitionTime,
Please use the DateLabel component here:
![Screenshot showing dates in ISO format](https://github.com/user-attachments/assets/f8063303-0293-4d62-81ba-20ae8599bc2c)

2025-01-29 14:35 UTC, joaquimrocha commented on cert-manager/src/index.tsx
> +  label: 'Cert-manager',
Maybe in lowercase as it's how it's used by the project: cert-manager

2025-01-30 10:53 UTC, yolossn commented
<img width="1624" alt="image" src="https://github.com/user-attachments/assets/0fc46f40-fc76-45e1-9646-4ee7a4ffd54d" />

Addressed the comments and added cert-manager not detected banner.

2025-02-06 02:02 UTC, knrt10 reviewed
Awesome work @yolossn. Apart from some suggestions, everything looks great

2025-02-06 02:02 UTC, knrt10 commented on cert-manager/.gitignore
> +.DS_Store
Can you please add new line here?

2025-02-06 02:02 UTC, knrt10 commented on cert-manager/README.md
> +Cert-manager plugin for Headlamp.
```suggestion
cert-manager plugin for Headlamp.
```

Since the project on there website is projected like this, let us also keep the naming convention the same. Apologies for the annoying nit but important for the naming convention. Can you please do that everywhere in the readme?

2025-02-06 02:02 UTC, knrt10 commented on cert-manager/package.json
> +}
Please add new line here

2025-02-06 02:02 UTC, knrt10 commented on cert-manager/README.md
> +   - Created/updated once the Challenge is successful
This should be indented inside right?

2025-02-06 02:02 UTC, knrt10 commented on cert-manager/README.md
> +- [Plugin Examples](https://github.com/headlamp-k8s/headlamp/tree/main/plugins/examples), Example plugins you can look at to see how it's done.
```suggestion
- [Getting Started](https://headlamp.dev/docs/latest/development/plugins/): How to create a new Headlamp plugin.
- [API Reference](https://headlamp.dev/docs/latest/development/api/): API documentation for what you can do
- [UI Component Storybook](https://headlamp.dev/docs/latest/development/frontend/#storybook): pre-existing components you can use when creating your plugin.
- [Plugin Examples](https://github.com/headlamp-k8s/headlamp/tree/main/plugins/examples): Example plugins you can look at to see how it's done.
```

2025-02-06 02:02 UTC, knrt10 commented on cert-manager/src/components/certificateRequests/Detail.tsx
> +                    navigator.clipboard.writeText(item.spec.request);
this returns a Promise that's not being handled. If the clipboard operation fails (which can happen due to permissions or technical issues), the error is silently ignored, can you please handle it with try and catch?

2025-02-06 02:02 UTC, knrt10 commented on cert-manager/src/components/challenges/Detail.tsx
> +                    navigator.clipboard.writeText(item.spec.key);
same, can you please handle error here?

2025-02-06 02:02 UTC, knrt10 commented on cert-manager/src/components/challenges/Detail.tsx
> +                            getter: item => item.ingress.class,
The getter function is accessing properties on the wrong object scope. Here, item represents the `http01` solver configuration, but the code is trying to access ingress.class directly without any null checks.
```suggestion
                            getter: http01Config => http01Config.ingress?.class
```

2025-02-06 02:02 UTC, knrt10 commented on cert-manager/src/components/clusterIssuers/Detail.tsx
> +                                    getter: item => item.ingress.class,
same, please fix the object scope

2025-02-06 02:02 UTC, knrt10 commented on cert-manager/src/components/issuers/Detail.tsx
> +                                    getter: item => item.ingress.class,
same please edit scope

2025-02-06 02:02 UTC, knrt10 commented on cert-manager/src/components/orders/Detail.tsx
> +                    navigator.clipboard.writeText(item.spec.request);
same, please check for errors here

2025-02-06 02:02 UTC, knrt10 commented on cert-manager/src/types/challenge.ts
> +      http01: {
according to cert-manager docs, should we also add for `dns01`?

2025-02-06 02:02 UTC, knrt10 commented on cert-manager/src/types/order.ts
> +  static isNamespaced = false;
these are namespaced resource
```suggestion
  static isNamespaced = true;
```

2025-02-06 07:31 UTC, yolossn commented on cert-manager/package.json
> +}
the default project formatting setting is removing the new line.

2025-02-06 07:34 UTC, yolossn commented on cert-manager/README.md
> +   - Created/updated once the Challenge is successful
![image](https://github.com/user-attachments/assets/702506df-9ee3-4c5a-b3a1-3a67d451d8da)
In preview it is appearing properly.

2025-02-06 12:07 UTC, sniok requested changes
good stuff! left a couple of comments

2025-02-06 12:07 UTC, sniok commented on cert-manager/src/components/certificateRequests/List.tsx
> +          getValue: certificateRequest => certificateRequest.approved,
for simple cases like this, it's better to use `datum` field like so:

```ts
 {
   id: 'approved',
   label: 'Approved',
   datum: 'approved',
}
```

2025-02-06 12:07 UTC, sniok commented on cert-manager/src/components/certificateRequests/List.tsx
> +  const [isManagerInstalled, setIsManagerInstalled] = useState(false);
this part (useState + useEffect) is repeated in each `List` component. please extract it into a it's own hook.

this starts with value false which will render NotInstalledBanner by default, even if it is installed. I'd recommend adding additional field `isManagerCheckLoading` that will keep track whether the check is still loading. this will avoid flashing "NotInstalledBanner" 

also this check is loaded every time you enter the page, it should be fetched once and remember the value

2025-02-06 12:07 UTC, sniok commented on cert-manager/src/index.tsx
> +registerSidebarEntry({
this pattern repeats here, `registerSidebarEntry` + `registerRoute` for Details and List could be put in a function

2025-02-06 12:07 UTC, sniok commented on cert-manager/src/types/certificate.ts
> +  static apiVersion = ['cert-manager.io/v1'];
apiVersion can be just a string, no need for an array here

2025-02-06 12:07 UTC, sniok commented on cert-manager/src/utils.ts
> +import { ApiProxy } from '@kinvolk/headlamp-plugin/lib';
this file could be named isCertManagerInstalled since there's nothing else here

2025-02-06 12:07 UTC, sniok commented on cert-manager/src/types/certificate.ts
> +import { KubeObject } from '@kinvolk/headlamp-plugin/lib/k8s/cluster';
/types/ folder name is a bit misleading. types usually means only typescript type definitions, here we define classes. Maybe /model/ would be better?

2025-02-17 07:16 UTC, yolossn commented on cert-manager/src/components/certificateRequests/Detail.tsx
> +                    navigator.clipboard.writeText(item.spec.request);
handled the error case

2025-02-17 07:16 UTC, yolossn commented on cert-manager/src/components/challenges/Detail.tsx
> +                    navigator.clipboard.writeText(item.spec.key);
done

2025-02-17 07:16 UTC, yolossn commented on cert-manager/src/components/orders/Detail.tsx
> +                    navigator.clipboard.writeText(item.spec.request);
done

2025-02-17 07:27 UTC, yolossn commented on cert-manager/src/components/certificateRequests/List.tsx
> +          getValue: certificateRequest => certificateRequest.approved,
fixed

2025-02-17 07:28 UTC, yolossn commented on cert-manager/src/types/certificate.ts
> +import { KubeObject } from '@kinvolk/headlamp-plugin/lib/k8s/cluster';
changed it to resource as in k8s follows that naming convention.

2025-02-17 07:40 UTC, yolossn commented on cert-manager/src/components/certificateRequests/List.tsx
> +  const [isManagerInstalled, setIsManagerInstalled] = useState(false);
Created a separate hook for this.

2025-02-17 09:45 UTC, illume requested changes
Left a couple of notes on some possible improvements for the README.

Documenting the components/functions/fields would be useful.

2025-02-17 09:45 UTC, illume commented on cert-manager/README.md
> +## Developing Headlamp plugins
Can you please remove this section?
(It's just there for new plugin authors)

2025-02-17 09:45 UTC, illume commented on cert-manager/README.md
> +cert-manager plugin for Headlamp.
Can you please add a bit more here? So people new to cert-manager will have more of an idea. Also what this plugin does for users evaluating the plugin.

- A screenshot or your video would be helpful too.
- What about adding a section for testing this plugin from the PR description?

@vyncent-t I know you have some good ideas on plugin README improvements... can you please review this README?

2025-02-21 09:21 UTC, joaquimrocha commented on cert-manager/README.md
> +cert-manager plugin for Headlamp.
The README has been updated with those suggestions.

2025-02-21 11:53 UTC, joaquimrocha approved these changes

2025-02-21 11:53 UTC, merged