app-catalog: Add default values to options
headlamp-k8s/plugins pull request #96
Opened 2024-10-30 19:19 UTC by skoeva

This change follows #94 by adding default values to the top options in the install UI. The namespace is set initially set to default and the description to `[app name] deployment`.

Fixes: #44 

### Testing
- [X] Open the app catalog within Headlamp and navigate to the install dialog
- [X] Ensure the top fields are filled with default values

![image](https://github.com/user-attachments/assets/5ca02352-9afe-49ed-8af6-705ac02e4e4c)

2024-10-31 16:13 UTC, joaquimrocha requested changes
@skoeva Thanks for the PR. I think this is not entirely doing what was intended: it does set the namespace by default but normally the UI doesn't show it as selected, which is misleading. I spent some times investigating and added a new commit for the version default which does set up the autocomplete (it's the defaultValue, and cannot just rely on the value of the version/namespace, but rather has to use the versions[0]/namespaces[0]).

Please adapt the 1st commit after this review.

2024-10-31 16:13 UTC, joaquimrocha commented on app-catalog/src/components/charts/EditorDialog.tsx
It says the namespace is set to default but it's setting it to the 1st namespace in the list. This is fine for now since I think we don't expose the loading of cluster settings to the plugins.

2024-10-31 16:13 UTC, joaquimrocha commented on app-catalog/src/components/charts/EditorDialog.tsx
> +  }, [namespaceNames]);
The `selectedNamespace` needs to be in the dependencies of this effect, else it will never use an updated value. See my commit with the version defaults.

2024-10-31 16:13 UTC, joaquimrocha commented on app-catalog/src/components/charts/EditorDialog.tsx
> +                setChartInstallDescription(`${chart.name} deployment`);
Can't this be removed too and the new default value added when we declare the effect?

2024-10-31 21:29 UTC, skoeva commented on app-catalog/src/components/charts/EditorDialog.tsx
I believe it is always at the top of the list, otherwise we could just search for it in the list but this seems like an unnecessary operation

2024-10-31 21:30 UTC, skoeva commented on app-catalog/src/components/charts/EditorDialog.tsx
> +  }, [namespaceNames]);
I think your commit might actually be breaking the default version. The initial change involved setting the selected version each time we opened a different app's install dialog, and now, since we only set it once in the `useEffect` at the top, this doesn't happen, so opening a different install dialog does not change the version number.

I also looked at the docs for Autocomplete, it seems that using `defaultValue` while having a React state is redundant, so I can make the change and lmk what you think

2024-11-02 01:54 UTC, illume approved these changes
👍 thanks

2024-11-02 01:54 UTC, merged